### ISSUE TITLE
Command piping

### ISSUE THREAD

**Issue by thebluefish** [thebluefish/bevy_commandify#11]
As mentioned in [this comment](https://github.com/thebluefish/bevy_commandify/issues/2#issuecomment-1934457829), we want commands that can pipe their results to some other system.

Example:
```rust
fn handle_foo_error(In(result): In<Result<(), FooError>>) {
    if let Err(error) = result {
        error!("Some error: {:?}", error);
    }
}

#[command(pipe = handle_foo_error)]
fn foo(world: &mut World, entity: Entity) -> Result<(), FooError> {
    bar(world, entity)?;
    Ok(())
}
```

For QoL, we would also like to handle the `Err` path explicitly, since most commands will not care to handle the `Ok` path:
```rust
fn handle_foo_error(In(error): In<FooError>, errors: ResMut<ErrorChannel>) {
    errors.send(error);
}

#[command(err = handle_foo_error)]
fn foo(world: &mut World, entity: Entity) -> Result<(), FooError> {
    bar(world, entity)?;
    Ok(())
}
```

---

Additional misc notes:

- We would need to change the special `-> Self` syntax to an attribute, to allow room for a `-> Result<T, E>`. This is something I low-key wanted to change last PR and will likely implement for this.
- Piped commands will need to be treated as wrapped systems in the same manner as system-commands. 

---

Do we want to be able to specify an `ok` path, too? As in 
```rs
#[command(ok = handle_ok, err = handle_foo_error)]
```
Might be equivalent to 
```rs
fn handle_foo(In(res): In<Result<(), FooError>>, world: &mut World) {
    match res {
        Ok(res) => world.run_system_once_with(res, handle_ok),
        Err(res) => world.run_system_once_with(res, handle_foo_errort),
    }
}

#[command(pipe = handle_foo)]
```

**Comment by brandon-reinhart** [comment]
I've started working on this in #12 

It works for error piping and I'm working on adding support for params now.

**Comment by brandon-reinhart** [comment]
One thing that might be useful is to pipe in the name of the command that failed, in the error handling case.

Ah, only zero or one input parameters are allowed so this probably isn't doable...

...or we could put the error information in a resource. GetLastError flashbacks...

**Comment by thebluefish** [comment]
> One thing that might be useful is to pipe in the name of the command that failed, in the error handling case.

I'm concerned that this might be too narrow. I think users could potentially seek several pieces of data, including the command name, TypeId (which would allow more detail through reflection), system name, and trait/method names. 

To outright create a struct of this info is against the grain - it would require us to restructure the crate to be a non-macro crate depending on a macro crate such as `bevy_commandify_macro`, so that we could export items like it.

> Ah, only zero or one input parameters are allowed so this probably isn't doable...

We can pack/unpack a tuple of `(our_data, error)`, though that would require the user to adjust their system's input accordingly.

I'm thinking perhaps we can decorate the handler attribute to define the shape of data the user wants, such as `#[command(err = foo_handler(command_name, system_name, error)]`, then the user's handler would be expected to take in an `In<(command_name, system_name, error)>: In<(&'static str, &'static str, Err<_>)>`.

If we did this route, `#[command(err = foo_handler]` would be equivalent to `#[command(err = foo_handler(error)]`

> ...or we could put the error information in a resource. GetLastError flashbacks...

We would probably have to require the user provide a unique resource name for each handler, perhaps it needs to impl some trait (exporting such a trait would be also against the grain). Without a macro on the handler itself [or something far more cursed](https://github.com/thebluefish/lightblue_automsg), there's really no other way I can think to generate the right bindings.

**Comment by brandon-reinhart** [comment]
I've added support for pipe = to the PR along with tests.
