### ISSUE TITLE
Feature gate wrappers

### ISSUE THREAD

**Issue by thebluefish** [thebluefish/bevy_commandify#14]
The original version of this crate was designed to be as thin as possible, covering only the necessary boilerplate that any user would need to write to transform an exclusive into an equivalent `Command` struct & `Commands` method.

Since then, we have added new features that do more than the bare minimum. Some of these features require that we keep the original system intact, and generate out own `Command::apply` method that runs that system. This operation adds overhead that I am uncomfortable with pushing people into blindly. UX-wise, there is little that we do that the user *wouldn't* to achieve the same effects, but making it convenient to compose as normal systems can encourage them to use a sub-optimal approach - exclusive systems and one-shot systems are a great alternative to commands depending on one's needs.

I would like to feature-gate anything beyond strict boilerplate, with a "full" feature to enable everything. I would prefer users opt-in to any costs, so we will default to no features enabled.

**Comment by brandon-reinhart** [comment]
This makes sense to me!
