### ISSUE TITLE
Optionally generate a public fn.

### ISSUE THREAD

**Issue by brandon-reinhart** [thebluefish/bevy_commandify#2]
Great crate. I'm using it extensively.

One pattern I find myself frequently doing is this:

```rust
#[command]
fn spawn_preview_ghost(world: &mut World, building_id: Id<Building>) {
    spawn_preview_ghost(world, building_id);
}

pub fn spawn_preview_ghost(world: &mut World, building_id: Id<Building>) {
    let building_manifest = world.get_resource::<BuildingManifest>().unwrap();
    let building_data = building_manifest.get(building_id).to_owned();
    let building_appearance = building_data.appearance;
    let y_sort_offset = building_data.y_sort_offset;

    let transform = Transform::from_xyz(0.0, 0.0, 0.0);

    let ghost = world
        .spawn((PreviewGhost { building_id }, YSort(y_sort_offset)))
        .id();

    // Make it look like the building.
    building_appearance.insert(world, ghost, transform, Anchor::BottomLeft);

    // Fade the sprite a bit.
    let _result = with_component_mut(world, ghost, |sprite: &mut Sprite| {
        sprite.color = Color::rgba(1.0, 1.0, 1.0, 0.5);
    });
}
```

For many of my commands, I will provide both a command and a public world function. Then I can compose functionality where I have world access or commands, as I please.

It might be neat if it was possible to have a flag on #[command] that indicated whether to generate a public fn that contains the meat of the command...

**Comment by brandon-reinhart** [comment]
I also sometimes do this:

```rust
#[command]
fn destroy_item_in_equip_slot(world: &mut World, character: Entity, equip_slot: Id<EquipSlot>) {
    let _result = destroy_item_in_equip_slot(world, character, equip_slot);
}

fn destroy_item_in_equip_slot(
    world: &mut World,
    character: Entity,
    equip_slot: Id<EquipSlot>,
) -> Result<(), ItemErrors> {
    use ItemErrors::*;

    let &character_id = get_component::<Id<Character>>(world, character)?;

    // The character must have the slot in question.
    let character_manifest = world.resource::<CharacterManifest>();
    let character_data = character_manifest.get(character_id);
    if !character_data.has_equip_slot(equip_slot) {
        return Err(CharacterDoesNotHaveEquipSlot);
    }
    
   /// ...
```
Where the naked version returns an error which the command reports or handles. I find this works well for transactional operations like working with items, where you want to check a bunch of invariants that might error before you commit the actual change.

**Comment by thebluefish** [comment]
> For many of my commands, I will provide both a command and a public world function. Then I can compose functionality where I have world access or commands, as I please.

Would it suffice to additionally implement the generated trait on `World`, too? #5 adds that.

> Where the naked version returns an error which the command reports or handles

I'm a bit uncomfortable doing any sort of magic error handling that doesn't bubble it up somehow, but I would be curious how such a thing might fit in.

**Comment by brandon-reinhart** [comment]
Definitely is nice to have the world version.

Won't cover all my cases, because I do frequently want the errors. I understand your discomfort, though.
